# .streamlit/secrets.toml

BACKEND_URL = "https://reviving-the-indian-cow-breed-a.onrender.com/predict/"  # <-- PASTE YOUR RENDER URL HERE   
GOOGLE_API_KEY="AIzaSyBEousgWPKyXJyKfxx38iw0KwX4Yjq2k_4"       # <-- PASTE YOUR GOOGLE KEY HERE